--- #YAML:1.0
name:               File-TTX
version:            0.03
abstract:           Utilities for dealing with TRADOS TTX files
author:
    - Michael Roberts <michael@vivtek.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    XML::xmlapi:  0.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
